# DEVELOPMENT version of docker-compose
# This will set up a database for us, and will tear it down when we're done.
# IMPORTANT: if you run "$ docker-compose down" you will lose all you database
# data.  That shouldn't really matter because it will just be test data.
version: "3"

services:
  backend:
    build:
      context: ./
    restart: always
    depends_on:
      - database
      - proxy
    ports:
      # Expose port 8080 of container to port 8081 of host
      - "8080:8080"
    env_file:
      - ./.env

  # The database will only be run in 
  database:
    image: postgres:11.3
    restart: always
    ports:
      # Expose port 3306 of container to port 8082 of host
      - "8082:3306"
    environment:
      POSTGRES_DB: bm


  proxy:
    image: nginx:1.15
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      # Expose port 80 of container to port 8080 of host
      - "8081:80"
