-- +goose Up
ALTER TABLE users
DROP COLUMN project_idea,
DROP COLUMN team_members;

CREATE TABLE schools (
	id SERIAL UNIQUE PRIMARY KEY NOT NULL,
	name TEXT
);

CREATE TABLE bm7_applications (
	id SERIAL UNIQUE PRIMARY KEY NOT NULL,
	decision SMALLINT NOT NULL,
	user_id INTEGER REFERENCES users(id),
	school_id INTEGER REFERENCES schools(id),
	gender TEXT,
	major TEXT,
	graduation_year TEXT,
	dietary_restrictions TEXT,
	github TEXT,
	linkedin TEXT,
	has_resume BOOLEAN,
	rsvp BOOLEAN,
	is_first_hackathon BOOLEAN,
	race TEXT,
	emailed_decision BOOLEAN,
	checked_in_at TIMESTAMP,
	shirt_size TEXT,
	project_idea TEXT,
	team_members TEXT[3],
	tac_18_or_older BOOLEAN,
	tac_mlh_code_of_conduct BOOLEAN,
	tac_mlh_contest_and_privacy BOOLEAN
);

-- Seed schools table
INSERT INTO schools (name)
VALUES
  ('Purdue University'),
  ('University of Texas-Dallas'),
  ('Rose-Hulman Institute of Technology'),
  ('University of Waterloo'),
  ('Oakland University'),
  ('Alaska Bible College'),
  ('Georgia State University'),
  ('University of Illinois-Urbana-Champaign'),
  ('Rensselaer Polytechnic Institute'),
  ('Pennsylvania State University'),
  ('Lawrence Technological University'),
  ('Poolesville High School'),
  ('University of British Columbia'),
  ('University of Wisconsin-Madison'),
  ('University of Pittsburgh'),
  ('University of California-Berkeley'),
  ('University of Illinois System'),
  ('Thomas Jefferson High School for Science and Technology'),
  ('Rutgers University-New Brunswick'),
  ('SUNY - Albany'),
  ('Ohio State University'),
  ('Henry M. Gunn High School'),
  ('Bergen County Academies - High School'),
  ('University of Louisville'),
  ('Georgia Institute of Technology'),
  ('University of Notre Dame'),
  ('Texas A&M University'),
  ('Carnegie Mellon University'),
  ('Michigan State University'),
  ('University of Michigan'),
  ('Illinois State University'),
  ('University of Texas-Pan American'),
  ('Suffolk University'),
  ('University of Texas-Austin'),
  ('City High School (Grand Rapids)'),
  ('Arcadia University'),
  ('University of Toronto'),
  ('Indiana University-Bloomington'),
  ('Marquette University'),
  ('Anderson University'),
  ('University of Chicago'),
  ('Cupertino High School'),
  ('Northwestern University'),
  ('Cornell University'),
  ('Purdue University-Calumet'),
  ('Mississippi State University'),
  ('Maumee Valley Country Day School'),
  ('McMaster University'),
  ('Virginia Polytechnic Institute & State University'),
  ('University of California-San Diego'),
  ('Kent State University'),
  ('Massachusetts Institute of Technology'),
  ('Southern Illinois University-Carbondale'),
  ('University of Missouri-Kansas City'),
  ('McGill University'),
  ('Rochester Institute of Technology'),
  ('University of Massachusetts-Amherst'),
  ('University of Pennsylvania'),
  ('The Roeper School'),
  ('Stanford University'),
  ('University of Wisconsin System'),
  ('University of California-Los Angeles'),
  ('Advanced Math and Science Academy Charter School'),
  ('University of Maryland - Baltimore County'),
  ('University of California-Irvine'),
  ('University of Cincinnati'),
  ('Youngstown State University'),
  ('University of Southern California'),
  ('University of Washington'),
  ('University of Colorado-Boulder'),
  ('Ball State University'),
  ('Illinois Institute of Technology'),
  ('Stevens Institute of Technology'),
  ('Iowa State University'),
  ('Purdue University College of Technology-Lafayette'),
  ('DePauw University'),
  ('Boston University'),
  ('Bowie State University'),
  ('University of Maryland - College Park'),
  ('New York University'),
  ('Wright State University'),
  ('Ravenwood High School'),
  ('Case Western Reserve University'),
  ('Temple University'),
  ('University of California-Santa Barbara'),
  ('International Academy East'),
  ('Southern Connecticut State University'),
  ('University of Windsor'),
  ('Old Dominion University'),
  ('University of Nebraska-Lincoln'),
  ('Vanderbilt University'),
  ('University of North Texas'),
  ('Minerva Schools'),
  ('University of Western Ontario'),
  ('North Dakota State University'),
  ('Drexel University'),
  ('University of Missouri'),
  ('University of Central Florida'),
  ('Cherry Hill High School East'),
  ('University of Iowa'),
  ('Columbia University'),
  ('Indiana Institute of Technology'),
  ('Vincent Massey Secondary School'),
  ('Florida State University'),
  ('The College of New Jersey'),
  ('Brandeis University'),
  ('Manhattan High School'),
  ('Manchester University'),
  ('Kent State University-Stark'),
  ('University of Virginia'),
  ('Brown University'),
  ('Fordham University'),
  ('William Rainey Harper College'),
  ('Parkland College'),
  ('Harvard University'),
  ('University of California-Santa Cruz'),
  ('Arizona State University'),
  ('University of Akron'),
  ('Alton High School'),
  ('New Jersey Institute of Technology'),
  ('Indiana University/Purdue University at Indianapolis'),
  ('Marcellus High School'),
  ('Brigham Young University'),
  ('West Windsor - Plainsboro High School North'),
  ('Wilkes University'),
  ('University of North Carolina-Chapel Hill'),
  ('Western Michigan University'),
  ('Fisk University'),
  ('Turner Fenton Secondary'),
  ('Ohio University'),
  ('Virginia Commonwealth University'),
  ('Embry-Riddle Aeronautical University'),
  ('Bridgewater State University'),
  ('Macalester College'),
  ('Fremont High School'),
  ('San Francisco State University'),
  ('College of Wooster'),
  ('Northeastern University'),
  ('University of Rochester'),
  ('SUNY - Buffalo'),
  ('University of Arkansas'),
  ('United States Naval Academy'),
  ('Santa Clara University'),
  ('Tufts University'),
  ('Indiana University/Purdue University at Fort Wayne'),
  ('University of Houston'),
  ('Pennsylvania State University-York'),
  ('SUNY - Stony Brook'),
  ('Howard University'),
  ('Miami Dade College'),
  ('Indian Institute of Technology'),
  ('Indiana Academy'),
  ('Sierra Nevada College'),
  ('California State University-Long Beach'),
  ('Southern Illinois University-Edwardsville'),
  ('Southern Methodist University'),
  ('Friedrich-Alexander University'),
  ('Glenaeon Rudolf Steiner School'),
  ('University of Illinois-Chicago'),
  ('Pennsylvania State University-Beaver'),
  ('California Polytechnic State University (San Luis Obispo)'),
  ('Stetson University'),
  ('Miami University'),
  ('AIB College of Business'),
  ('High Point Central High School'),
  ('Foothill College'),
  ('Hampton University'),
  ('University of Alabama-Huntsville'),
  ('Istituto Salesiani Don Bosco'),
  ('University of Arizona'),
  ('San JosÃ© State University'),
  ('Blue Valley Northwest'),
  ('Johnson C. Smith University'),
  ('Knox College'),
  ('University of Michigan-Dearborn'),
  ('Mission San Jose High School'),
  ('Stuyvesant High School'),
  ('Carleton College'),
  ('Smith College'),
  ('SUNY - Binghamton'),
  ('University of Florida'),
  ('Marymount International School Rome'),
  ('Monmouth University'),
  ('Queen''s University'),
  ('Earlham College'),
  ('Middle Tennessee State University'),
  ('Washington University in St. Louis'),
  ('Boston College'),
  ('Milwaukee School of Engineering'),
  ('University of Kentucky'),
  ('Claremont McKenna College'),
  ('Eastern Michigan University'),
  ('New College of Florida'),
  ('Hamilton College'),
  ('Yale University'),
  ('The City University of New York'),
  ('The George Washington University'),
  ('Texas Christian University'),
  ('Michigan Technological University'),
  ('Butler University'),
  ('Worcester Polytechnic Institute'),
  ('Florida International University'),
  ('University of Miami'),
  ('Valparaiso University'),
  ('Loyola University Chicago'),
  ('Rice University'),
  ('Other/School not listed');

-- +goose Down
ALTER TABLE users
ADD COLUMN project_idea TEXT,
ADD COLUMN team_members TEXT[3];

DROP TABLE schools;
DROP TABLE bm7_applications;
