version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: "get versions"
        command: |
          docker version
          docker-compose --version
    - run:
        name: "docker-compose up"
        command: |
          docker-compose -f deploy/docker-compose.base.yml -f deploy/docker-compose.testing.yml up -d
    - run:
        name: "run tests"
        command: |
          docker-compose -f deploy/docker-compose.base.yml -f deploy/docker-compose.testing.yml exec backend go test -v ./...
