# PRODUCTION version of docker-compose configuration
# This file extends docker-compose.base.yml
version: "3"
services:
  backend:
    build:
      context: ../
      dockerfile: ./deploy/backend.docker

  database:
    env_file:
      - ../.env
    volumes:
      - /var/lib/pgsql/data:/var/lib/postgresql/data

  proxy:
    ports:
      # Expose port 80  of container to port 80  of host (HTTP)
      - 80:80
      # Expose port 443 of container to port 443 of host (HTTPS)
      - 443:443
    env_file:
      - ../.env
    command:
      - --acme.email=${TRAEFIK_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.prod.toml:/etc/traefik/traefik.toml
      - /opt/traefik/acme.json:/acme.json
