# BASE version of docker-compose configuration
# Dev, prod, and testing will build off of this file
version: "3"
services:
  backend:
    build:
      context: ../
      dockerfile: ./deploy/backend.base.docker
    restart: always
    volumes:
      - ../:/backend
    depends_on:
      - database
      - proxy
    labels:
      - traefik.enable=true
      - traefik.backend=backend
      - traefik.frontend.rule=Host:www.${DOMAIN_NAME},${DOMAIN_NAME}
      - traefik.port=8080

  database:
    build:
      context: ../
      dockerfile: ./deploy/database.docker
    restart: always
    labels:
      - traefik.enable=false
    ports:
      # Expose port 5432 of container to port 47298 of host
      # Useful for using Sequel Pro or pgweb to inspect the db
      - "47298:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  proxy:
    image: traefik:1.7-alpine
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:dashboard.${DOMAIN_NAME}
      - traefik.frontend.auth.basic=${TRAEFIK_DASHBOARD_LOGIN}
