# DEVELOPMENT version of docker-compose configuration
# This file extends docker-compose.base.yml
#
# TODO if developing with docker is v slower then this can just 
# host the database with docker and build the backend like normal
version: "3"
services:
  backend:
    volumes:
      - ../.env:/backend/.env

  database:
    env_file:
      - ../.env

  proxy:
    ports:
      # Expose port 80 of container to port 8080 of host
      - "8080:80"
