# PRODUCTION version of docker-compose configuration
# This file extends docker-compose.base.yml
version: "3"
services:
  backend:
    volumes:
      - ../.env:/backend/.env

  database:
    env_file:
      - ../.env

  proxy:
    ports:
      # Expose port 80  of container to port 80  of host (HTTP)
      - "80:80"
      # Expose port 443 of container to port 443 of host (HTTPS)
      - "443:443"
